[versions]
modDevGradle = "2.0.99"
neoForge = "21.1.186"
minecraft = "1.21.1"
parchment = "2024.11.17"
lombok = "8.7.1"
anvilcraft = "1.5.0+pre-release.22"

[libraries]
anvilcraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-1.21.1", version.ref = "anvilcraft" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }